spring:
  artemis:
    mode: embedded
    embedded:
      enabled: true
      queues: quickstart-messages
      persistent: true

  datasource: 
    url: jdbc:h2:file:./target/quickstart-database
    jpa:
      hibernate:
        ddl-auto: update

  jta:
    log-dir: ./target/tx-object-store
    narayana:
      periodic-recovery-period: 2
      recovery-backoff-period: 1

my:
  datasources:
    url: jdbc:postgresql://localhost:5432/
    user: postgres
    password: postgres
    list:
    - name: datasourceOne
      url: jdbc:postgresql://localhost:5432/databaseOne
    - name: datasourceTwo
      url: jdbc:postgresql://localhost:5432/databaseTwo
    - name: datasource
      url: jdbc:postgresql://localhost:5432/database