spring:
  artemis:
    mode: embedded
    embedded:
      enabled: true
      queues: quickstart-messages
      persistent: true
      
  datasource: 
    url: jdbc:h2:file:./target/quickstart-database
    jpa:
      hibernate:
        ddl-auto: update

  jta:
    log-dir: ./target/tx-object-store
    narayana:
      periodic-recovery-period: 2
      recovery-backoff-period: 1
      default-timeout: -1
        
my:
  datasources:
    default-property:
      detail:
        url: jdbc:postgresql://localhost:5432/
        user: postgres
        password: postgres
    list:
    - name: datasourceOne
      detail:
        url: jdbc:postgresql://localhost:5432/databaseOne
    - name: datasourceTwo
      detail:
        url: jdbc:postgresql://localhost:5432/databaseTwo
    - name: datasource
      detail:
        url: jdbc:postgresql://localhost:5432/database